### ISSUE TITLE
attempt to call 'require' (a nill value)

### ISSUE THREAD

**Issue by itsfolf** [MetallEast/OpenComputers-chat#1]
![image](https://cloud.githubusercontent.com/assets/9268058/16703679/79d59892-4567-11e6-9e87-74aa6a2d2f90.png)

**Comment by MetallEast** [comment]
thread.lua is not a standard library. Before running the client or server create it using the 
following code ([link](http://pastebin.com/E0SzJcCx))

**Comment by itsfolf** [comment]
Where should I create a file with that code? bin?

**Comment by MetallEast** [comment]
lib
