### ISSUE TITLE
Not working on OC 1.6 and above

### ISSUE THREAD

**Issue by ExFallenSkyTear** [MetallEast/OpenComputers-chat#10]
As stated in the "Known issue" section, the script do not work as expected since OC 1.6.
I debugged it for a couple of hours and traced the issue in the CLient.lua file.
Precisely, the problem resides in the "Recivers" function, from line 128 to line 140, it has some problems in the Online list section.
By commenting out those lines I could get it to work as intended.
I still don't know why those lines break the code, but I would like to fix it in the near future.

Hope this is helpfull if someone want to use this script or the creator wants to fix this issue.

**Comment by MetallEast** [comment]
@ExFallenSkyTear not able to dive into open computers in near future but I appreaciate an upcoming pr with fix if you're going to fix it. Thanks for investigation!

**Comment by MetallEast** [comment]
Seems to be fixed #11
